# NumPy Beginner Guide 02 - Numpy的解决方案

## 向量

In [6]:
## 用arange创建一个向量
import numpy as np
a = np.arange(5)
a.dtype

# Notice:
# 在Packt NumPy Beginner Guide中作者的返回值是dtype('int64')
# 但在我的环境上是dtype('int32')。这一点不足为奇，因为各个
# 电脑的配置都是不同的。

dtype('int32')

In [7]:
## 获取维度
import numpy as np
a = np.array([1,2,3,4,5])
a.shape

(5,)

## 创建多维向量

In [14]:
## 2*2的向量
from numpy import array
a = array([array([1,2]), array([3,4])])
a.shape

(2, 2)

In [18]:
## 3*3的向量
## Have a go hero – create a three-by-three array
from numpy import array
matrix = array([array([1,2,3]),array([4,5,6]),array([7,8,9])])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 选择向量里的元素

In [19]:
## Jedi: 书里面用的是整数，我这里用字符串
from numpy import array
m = array([array(['林海洪', '周颢']), array(['张涛', '林雄'])])
print(m[0,0], m[0,1], m[1,0], m[1,1])
print(m.shape)

林海洪 周颢 张涛 林雄
(2, 2)


## 向量元素的类型

In [22]:
# 用这个方法可以获得某个类型的取值范围
import numpy as np
np.finfo(np.float16)

finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)

In [42]:
# 其他的numpy类型的举例
import numpy as np
f64 = np.float64(42); print(f64, '->', type(f64))
i8 = np.int8(42.0);   print(i8,  '->', type(i8))
bt = np.bool(42);     print(bt,  '->', type(bt))
bf = np.bool(0);      print(bf,  '->', type(bf))
ft = np.float(True);  print(ft,  '->', type(ft))
ff = np.float(False); print(ff,  '->', type(ff))

42.0 -> <class 'numpy.float64'>
42 -> <class 'numpy.int8'>
True -> <class 'bool'>
False -> <class 'bool'>
1.0 -> <class 'float'>
0.0 -> <class 'float'>


In [43]:
# 创建向量时指定类型
import numpy as np
m = np.arange(7, dtype=np.float64)
print(m, '-> dtype: ', m.dtype)
print(type(m))

[0. 1. 2. 3. 4. 5. 6.] -> dtype:  float64
<class 'numpy.ndarray'>


### 数据类型对象

In [45]:
# 查看数据类型的itemsize
import numpy as np
m = np.arange(7, dtype=np.int8)
m.dtype.itemsize

1

In [65]:
# 如果用python的内置类型
import numpy as np
m = np.array([array(['张涛', '刘进勇']),array(['昕哥', '大波'])])
print(m)
print(m.shape)
print(type(m))
print(m.dtype, m.dtype.itemsize)
print(len(u'刘进勇'))
print(len(m))
# 看到啦！直接给我们撸成了Unicode

[['张涛' '刘进勇']
 ['昕哥' '大波']]
(2, 2)
<class 'numpy.ndarray'>
<U3 12
3
2


### 类型编码

In [95]:
# 各种缩写的举例
# Jedi, 不过我更喜欢完整的写法->更有逻辑些嘛~
import numpy as np
def print_dtype(n):
    print('->', n, ', n.dtype', n.dtype)
array_int  = np.arange(7, dtype='i');    print_dtype(array_int)
array_sing = np.arange(7, dtype='f');    print_dtype(array_sing)
array_dobl = np.arange(7, dtype='d');    print_dtype(array_dobl)
array_comp = np.arange(7, dtype='D');    print_dtype(array_comp)

# Jedi: 注意在Python3的numpy中不能这样使用
# array_uint = np.arange(7, dtype='u');  print_dtype(array_uint)
# array_bool = np.arange(7, dtype='b');  print_dtype(array_bool)
# array_str  = np.arange(7, dtype='S');  print_dtype(array_str)
# array_uni  = np.arange(7, dtype='U');  print_dtype(array_uni)
# array_void = np.arange(7, dtype='V');  print_dtype(array_void)

-> [0 1 2 3 4 5 6] , n.dtype int32
-> [0. 1. 2. 3. 4. 5. 6.] , n.dtype float32
-> [0. 1. 2. 3. 4. 5. 6.] , n.dtype float64
-> [0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j] , n.dtype complex128


### 类型的默认值

In [96]:
import numpy as np
np.dtype(float)

dtype('float64')

In [97]:
import numpy as np
np.dtype('f')

dtype('float32')

In [98]:
import numpy as np
np.dtype('d')

dtype('float64')

In [99]:
import numpy as np
np.dtype('f8')

dtype('float64')

In [100]:
# 类型枚举
# Jedi: God! 这也太多了吧!
import numpy as np
np.sctypeDict.keys()

dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 'uintp', 'P', 'long', 'l', 7, 'L', 8, 'longlong', 'q', 9, 'ulonglong', 'Q', 10, 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'Bool', 'b1', 'float16', 'Float16', 'f2', 'float32', 'Float32', 'f4', 'float64', 'Float64', 'f8', 'complex64', 'Complex32', 'c8', 'complex128', 'Complex64', 'c16', 'object0', 'Object0', 'bytes0', 'Bytes0', 'str0', 'Str0', 'void0', 'Void0', 'datetime64', 'Datetime64', 'M8', 'timedelta64', 'Timedelta64', 'm8', 'int32', 'uint32', 'Int32', 'UInt32', 'i4', 'u4', 'int64', 'uint64', 'Int64', 'UInt64', 'i8', 'u8', 'int16', 'uint16', 'Int16', 'UInt16', 'i2', 'u2', 'int8', 'uint8', 'Int8', 'UInt8', 'i1', 'u1', 'complex_', 'int0', 'uint0', 'single', 'csingle', 'singlecomplex', 'float_', 

### dtype属性

In [16]:
# 获取属性
from numpy import *
d = dtype('f8')
print(d.type)
print(d.char)

<class 'numpy.float64'>
d


## 创建类型

In [28]:
# Jedi: 类型有点像是class，或struct
# Notice 1: 注意在Windows上用Python3有些类似似乎支持不了
# Notice 2: 使用了不太规则的缩进，主要是为了可以看清楚
import numpy as np
t = np.dtype([
    ('name', str, 40),
    ('numtimes', 'i8'),
    ('price', 'f8')
])
print(t['name'])
print(t['numtimes'])
print(t['price'])

<U40
int64
float64


In [37]:
# Jedi: 既然有了类型，那么我们具体的“实例”
import numpy as np
emptype = np.dtype([
    ('name', str, 40),
    ('age', 'i'),
    ('salary', 'f')
])

# 把tom和jerry的年龄和工资晒出来
tom_jerry = array([
    ('jerry', 28, 28000),
    ('tom', 29, 13500)
], dtype=emptype)

# 做下简单的输出
for actor in tom_jerry:
    print("%s的年龄是%i，工资是$%f" % (actor['name'], actor['age'], actor['salary']))

jerry的年龄是28，工资是$28000.000000
tom的年龄是29，工资是$13500.000000


### 一纬向量的切片和索引

In [41]:
# 切片
a = list(range(9))
print(a[3:7])
print(a[:7:2])
print(a[::-1])

[3, 4, 5, 6]
[0, 2, 4, 6]
[8, 7, 6, 5, 4, 3, 2, 1, 0]


### 多维向量的切片和索引

In [47]:
# 第1步：创建多维向量
import numpy as np
b = np.arange(24).reshape(2,3,4)
print(b.shape)
print(b)

(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [51]:
# 第2步：使用位置的绝对位置来索引元素
import numpy as np
b = np.arange(24).reshape(2,3,4)
print(b[0,0,0])
print(b[1,2,3])

0
23


In [55]:
# 第3步骤: 向量的切片
import numpy as np
b = np.arange(24).reshape(2,3,4)
print(b[:,0,0])  # 取每个一级元素的[0,0]位
print(b[0])      # 取第一个元素
print(b[0,::])   # 取第一元素的另外一种取法
print(b[0, ...]) # 这个方法更聪明

[ 0 12]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [56]:
# 第4步: 行切片
import numpy as np
b = np.arange(24).reshape(2,3,4)
print(b[0,1,::2])

[4 6]


In [63]:
# 第5步：使用省略号的切片
import numpy as np
b = np.arange(24).reshape(2,3,4)
print(b); print()
print(b[..., 1]); print() # 取所有表格的第二列
print(b[:,1]); print()    # 取所有表格的第二行
print(b[0,:,1])           # 取第一個表格的第二列

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

[[ 1  5  9]
 [13 17 21]]

[[ 4  5  6  7]
 [16 17 18 19]]

[1 5 9]


In [69]:
# 第6步: 使用负号的进行切片操作
import numpy as np
b = arange(24).reshape(2,3,4)
print(b[0,:,-1]);    print()  # 取第一个表格的最后一列
print(b[0,::-1,-1]); print()  # 将第一个表格行次序颠倒过来，然后取其最后一列
print(b[0,::2, -1]); print()  # 取第一个表格前两行的最后一列
print(b[::-1])                # 将表格次序颠倒过来, 但元素的位置不变

[ 3  7 11]

[11  7  3]

[ 3 11]

[[[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


## 维度操作

In [73]:
# 1. ravel函数
import numpy as np
matrix = np.arange(24).reshape(2,3,4)
print(matrix); print()
print(matrix.ravel()); print()

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]



In [76]:
# 2. faltten函数
import numpy as np
matrix = np.arange(24).reshape(2,3,4)
print(matrix); print()
print(matrix.flatten())

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [78]:
# 3. 通过设置shape属性变更维度
import numpy as np
m = np.arange(24).reshape(2,3,4)
m.shape = (6,4); print(m); print()
m.shape = (3,8); print(m); print()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]



In [83]:
# 4. transpose()函数
import numpy as np
m = np.arange(24).reshape(6,4)
print(m); print()
print(m.transpose())  # 也即->行转列，列转行

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[ 0  4  8 12 16 20]
 [ 1  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]]


In [85]:
# 5. resize()函数
# Jedi: 相当于用直接改shape属性
import numpy as np
m = np.arange(24).reshape(6,4)
m.resize((2,12)); print(m)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]


## 行列式操作

In [90]:
# 后面的操作基于这两个行列式
import numpy as np
a, b = np.arange(9).reshape(3,3), 2*a
print(a); print(); print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [96]:
# 1. 行列式水平合并
import numpy as np
a, b = np.arange(9).reshape(3,3), 2*a
c = np.hstack((a, b)); print(c)

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]


In [97]:
# 2. 行列式垂直合并-使用vstack
import numpy as np
a, b = np.arange(9).reshape(3,3), 2*a
c = np.vstack((a,b)); print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [99]:
#2. 行列式垂直合并-使用concatenate()
import numpy as np
a, b = np.arange(9).reshape(3,3), 2*a
c = np.concatenate((a,b), axis=0); print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [110]:
#3. 行列式的深度合并
#Jedi: 我用的词应该不准确 （哈哈哈）
import numpy as np
a, b = np.arange(9).reshape(3,3), 2*a
c = np.dstack((a, b)); print(c); print(c.shape)

[[[ 0  0]
  [ 1  2]
  [ 2  4]]

 [[ 3  6]
  [ 4  8]
  [ 5 10]]

 [[ 6 12]
  [ 7 14]
  [ 8 16]]]
(3, 3, 2)


In [121]:
#4. 行列式的列操作
import numpy as np
a = np.arange(2)
b = 2 * a
c = np.column_stack((a,b))
print(c)

[[0 0]
 [1 2]]
